Increase the number of outbound peers
ssvlabs/ssv pull request #1236
Opened 2023-12-11 16:52 UTC by GalRogozinski

From a default of 2 increase to 4.

This is the maximal allowed according to the [libp2p docs](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#outbound-mesh-quotas)

2023-12-14 03:17 UTC, MatheusFranco99 approved these changes

2023-12-17 10:17 UTC, y0sher commented on .gitlab-ci.yml
> +    - dout
revert the deployment

2023-12-20 08:22 UTC, GalRogozinski commented on .gitlab-ci.yml
> +    - dout
done

2023-12-28 13:33 UTC, lior-blox requested changes
Please add a summary that explains why we need to change this value

2023-12-28 13:43 UTC, GalRogozinski commented
@lior-blox done

2024-01-02 10:47 UTC, MatheusFranco99 approved these changes

2024-01-02 13:45 UTC, y0sher approved these changes
Generally I understand why increasing outbound connections might reduce the chance for an eclipse attack. but at the same time, I don't get how you came up we are vulnerable to it, what made you want to make this change. did you check how this change affect and realize it protects us in any way?

2024-01-03 13:18 UTC, y0sher approved these changes

2025-08-10 02:13 UTC, closed without merging