Storage improve coverage
ssvlabs/ssv pull request #1312
Opened 2024-02-08 12:47 UTC by pavelkrolevets

* add more unit test to /storage

coverage: 78.9% of statements

2024-02-12 16:11 UTC, nkryuchkov commented on storage/kv/badger_test.go
> +	for i = 0; i < 100; i++ {
```suggestion
	for i := uint64(0); i < 100; i++ {
```

2024-02-12 16:11 UTC, nkryuchkov commented on storage/kv/badger_test.go
> +	err = db.GetMany(prefix, [][]byte{}, func(obj basedb.Obj) error {
This would be a bit more readable with a newline
```suggestion
	
	err = db.GetMany(prefix, [][]byte{}, func(obj basedb.Obj) error {
```

2024-02-12 16:11 UTC, nkryuchkov commented on storage/kv/badger_test.go
> +	require.NoError(t, err)
```suggestion
	require.NoError(t, err)
	
```

2024-02-12 16:11 UTC, nkryuchkov commented on storage/kv/badger_test.go
> +	require.NoError(t, err)
```suggestion
	require.NoError(t, err)
	
```

2024-02-12 16:11 UTC, nkryuchkov commented on storage/kv/txn_test.go
> +	db, err := NewInMemory(logger, options)
it's a bit hard to follow the logic without splitting code blocks with newlines

2024-04-08 15:26 UTC, y0sher commented on storage/kv/txn_test.go
> +	require.Equal(t, 100, len(visited))
I would rather we check all the values instead just the length

2024-04-08 15:26 UTC, y0sher requested changes
minor addition

2025-03-31 18:08 UTC, kchojn commented
Closed by: https://github.com/ssvlabs/ssv/pull/2094

2025-03-31 18:08 UTC, closed without merging