upgrade go-ethereum to v1.13.14
ssvlabs/ssv pull request #1369
Opened 2024-04-10 14:25 UTC by guym-blox

2024-04-11 10:53 UTC, y0sher commented on network/discovery/dv5_logger.go
> +//}
is this not used anymore? is `dvlogger` enough? please remove commnet.

2024-04-11 10:54 UTC, y0sher requested changes
remove old comments and test on stage pls.

2024-04-14 12:21 UTC, y0sher approved these changes

2024-04-16 14:10 UTC, y0sher approved these changes

2024-04-16 14:16 UTC, moshe-blox approved these changes

2024-04-16 14:18 UTC, moshe-blox commented on network/discovery/logger/md5_logger.go
> +package compatibale_logger
```suggestion
package compatible_logger
```

2024-04-16 14:54 UTC, y0sher approved these changes

2024-04-16 14:54 UTC, merged