fix: find host address using dig
ssvlabs/ssv pull request #1375
Opened 2024-04-18 11:37 UTC by y0sher

### Fix

In our Makefile we are setting HOST_ADDRESS env to pass to the node in order to advertise itself in discovery. when we introduced #1358 , we switched to using a different image in docker and this image lacks `dig` which is the utility we use to resolve our address against a dns service.

this installs dnsutils which has dig so we could get our address.

2024-04-18 13:53 UTC, nkryuchkov submitted a review, later dismissed

2024-04-24 09:19 UTC, zktaiga requested changes
Can you please pin the version of dnsutils? Looks good otherwise.

2024-04-24 09:24 UTC, zktaiga commented on Dockerfile
> +  dnsutils \
```suggestion
  dnsutils=1:9.18.24-1 \
```

2024-05-02 12:44 UTC, zktaiga approved these changes

2024-05-19 13:51 UTC, moshe-blox approved these changes

2024-05-19 14:02 UTC, merged