Added stop committee runner queue consumption trigger
ssvlabs/ssv pull request #1436
Opened 2024-06-19 11:47 UTC by AKorpusenko

…ached

2024-06-24 10:18 UTC, y0sher commented on protocol/v2/ssv/runner/committee.go
> +	stopCh chan struct{}
why is this here if it has no meaning for the committee runner itself?

2024-06-24 10:18 UTC, y0sher commented on protocol/v2/ssv/validator/committee_queue.go
> +	stopCh <-chan struct{},
should've probably just used a context dedicated to this slot queue.

2024-06-24 10:19 UTC, y0sher requested changes
create a context when you create the queue and pass it in.

2024-06-25 11:44 UTC, AKorpusenko commented on protocol/v2/ssv/validator/committee_queue.go
> +		}
Added. Thanks

2024-06-25 12:18 UTC, y0sher commented on protocol/v2/ssv/validator/committee_queue.go
> +
`StartDuty` is already locking, so this is potential "deadlock" or just double locking, although this happens in a goroutine and the lock is released in start duty. Still I think its better to just pass the Queue `q` from `StartDuty` as we're already using the mutex to get it there.

by passing it to this function you don't need to use the mutex here at all.

2024-06-25 12:21 UTC, y0sher commented on operator/validator/controller.go
> +			}
you can't do this here, accessing Queues requires mutex acquiring. best is to have a function inside the committee struct that handles this.

2024-06-25 12:32 UTC, y0sher requested changes
concurrency issues..

2024-06-25 13:47 UTC, y0sher commented on operator/validator/controller.go
> +			vc.StopQueues()
`Stop` or `Close` is more appropriate

2024-06-25 14:18 UTC, y0sher commented on protocol/v2/ssv/validator/events.go
> +		if !exists {
```suggestion
		q, exists := c.Queues[slot]
		dutyRunner, exists := c.Runners[slot]
		c.mtx.Unlock()
		if !exists || !qexists {
```

queue should be present if there's a runner but lets be on the safe side anyway.

2024-06-25 14:21 UTC, y0sher requested changes
small change

2024-06-25 14:38 UTC, y0sher approved these changes

2024-08-01 13:17 UTC, moshe-blox commented on protocol/v2/ssv/validator/events.go
> +		q.StopQueueF()
why are we stopping the queue on timeout message?

2024-08-05 13:50 UTC, AKorpusenko commented
Replaced with PR https://github.com/ssvlabs/ssv/pull/1556 based on the `stage` branch

2024-08-05 13:50 UTC, closed without merging