Gm/no fork lint fix
ssvlabs/ssv pull request #1447
Opened 2024-07-03 12:51 UTC by guym-blox

2024-07-16 20:57 UTC, y0sher commented
There are still lint errors if you run `make lint` or look at CI lint report.
they are not related to spec tests.

@guym-blox 

```
INFO [runner] linters took 14.88702675s with stages: goanalysis_metalinter: 14.744550208s 
network/topics/container.go:1: : # github.com/ssvlabs/ssv/network/topics [github.com/ssvlabs/ssv/network/topics.test]
network/topics/controller_test.go:70:27: undefined: validation.NewMessageValidator
network/topics/controller_test.go:375:45: not enough arguments in call to NewPubSub
        have (context.Context, *zap.Logger, *PubSubConfig, metricsreporter.MetricsReporter)
        want (context.Context, *zap.Logger, *PubSubConfig, Metrics, CommitteesProvider)
network/topics/controller_test.go:425:19: undefined: specqbftSignedMessage
network/topics/msg_validator_test.go:53:19: undefined: validation.NewMessageValidator
network/topics/msg_validator_test.go:53:77: undefined: validation.WithNodeStorage
network/topics/msg_validator_test.go:92:39: undefined: spectypes.EncodeSignedSSVMessage
network/topics/msg_validator_test.go:93:54: ssvMsg.GetID().GetPubKey undefined (type "github.com/ssvlabs/ssv-spec/types".MessageID has no field or method GetPubKey) (typecheck)
package topics
protocol/v2/testing/test_utils.go:121:18: Error return value of `file.Close` is not checked (errcheck)
        defer file.Close()
                        ^
protocol/v2/testing/test_utils.go:127:24: Error return value of `gzipReader.Close` is not checked (errcheck)
        defer gzipReader.Close()
                              ^
protocol/v2/testing/test_utils.go:280:17: Error return value of `outFile.Close` is not checked (errcheck)
                        outFile.Close()
                                     ^
protocol/v2/testing/test_utils.go:295:14: Error return value of `errors.Wrap` is not checked (errcheck)
                errors.Wrap(err, "could not open file")
                           ^
protocol/v2/ssv/validator/committee.go:145:19: Error return value of `c.ConsumeQueue` is not checked (errcheck)
        go c.ConsumeQueue(logger, duty.Slot, c.ProcessMessage, c.Runners[duty.Slot])
                         ^
protocol/v2/testing/test_utils.go:117:15: G304: Potential file inclusion via variable (gosec)
        file, err := os.Open(gzPath)
                     ^
protocol/v2/testing/test_utils.go:269:14: G301: Expect directory permissions to be 0750 or less (gosec)
                        if err := os.Mkdir(header.Name, 0755); err != nil {
                                  ^
protocol/v2/testing/test_utils.go:277:17: G110: Potential DoS vulnerability via decompression bomb (gosec)
                        if _, err := io.Copy(outFile, tarReader); err != nil {
                                     ^
protocol/v2/ssv/spectest/debug_states.go:52:8: G306: Expect WriteFile permissions to be 0600 or less (gosec)
        err = os.WriteFile(fmt.Sprintf("%s/%s_test_serialized.json", dumpDir, name), bytes, 0644)
              ^
protocol/v2/testing/test_utils.go:292:6: func `unpackTestsJson` is unused (unused)
func unpackTestsJson(path string) error {
     ^
protocol/v2/qbft/instance/instance.go:30:2: field `started` is unused (unused)
        started time.Time
        ^
protocol/v2/qbft/instance/instance.go:66:6: func `messageIDFromBytes` is unused (unused)
func messageIDFromBytes(mid []byte) spectypes.MessageID {
     ^
message/validation/consensus_validation.go:333:29: func `(*messageValidator).maxSlotsInState` is unused (unused)
func (mv *messageValidator) maxSlotsInState() phase0.Slot {
                            ^
protocol/v2/ssv/validator/committee.go:320:21: func `(*Committee).updateAttestingSlotMap` is unused (unused)
func (c *Committee) updateAttestingSlotMap(duty *spectypes.CommitteeDuty) {
                    ^
operator/validator/controller.go:194:2: field `recentlyStartedCommittees` is unused (unused)
        recentlyStartedCommittees uint64
        ^
operator/validator/controller.go:893:6: type `starter` is unused (unused)
type starter interface {
     ^
protocol/v2/ssv/spectest/msg_processing_type.go:172:36: func `(*MsgProcessingSpecTest).compareBroadcastedBeaconMsgs` is unused (unused)
func (test *MsgProcessingSpecTest) compareBroadcastedBeaconMsgs(t *testing.T) {
                                   ^
protocol/v2/testing/test_utils.go:256:2: S1006: should use for {} instead of for true {} (gosimple)
        for true {
        ^
network/topics/params/message_rate.go:113:5: S1009: should omit nil check; len() for []*github.com/ssvlabs/ssv/registry/storage.Committee is defined as zero (gosimple)
        if committees == nil || len(committees) == 0 {
           ^
protocol/v2/ssv/testing/runner.go:110:10: S1040: type assertion to the same type: runner.NewCommitteeRunner(
        networkconfig.TestNetwork,
        shareMap,
        contr,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
        valCheck,
) already has type runner.Runner (gosimple)
                return runner.NewCommitteeRunner(
                       ^
protocol/v2/ssv/testing/runner.go:121:10: S1040: type assertion to the same type: runner.NewAggregatorRunner(
        spectypes.BeaconTestNetwork,
        shareMap,
        contr,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
        valCheck,
        TestingHighestDecidedSlot,
) already has type runner.Runner (gosimple)
                return runner.NewAggregatorRunner(
                       ^
protocol/v2/ssv/testing/runner.go:133:10: S1040: type assertion to the same type: runner.NewProposerRunner(
        spectypes.BeaconTestNetwork,
        shareMap,
        contr,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
        valCheck,
        TestingHighestDecidedSlot,
) already has type runner.Runner (gosimple)
                return runner.NewProposerRunner(
                       ^
protocol/v2/ssv/testing/runner.go:145:10: S1040: type assertion to the same type: runner.NewSyncCommitteeAggregatorRunner(
        spectypes.BeaconTestNetwork,
        shareMap,
        contr,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
        valCheck,
        TestingHighestDecidedSlot,
) already has type runner.Runner (gosimple)
                return runner.NewSyncCommitteeAggregatorRunner(
                       ^
protocol/v2/ssv/testing/runner.go:157:10: S1040: type assertion to the same type: runner.NewValidatorRegistrationRunner(
        spectypes.BeaconTestNetwork,
        shareMap,
        contr,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
) already has type runner.Runner (gosimple)
                return runner.NewValidatorRegistrationRunner(
                       ^
protocol/v2/ssv/testing/runner.go:167:10: S1040: type assertion to the same type: runner.NewVoluntaryExitRunner(
        spectypes.BeaconTestNetwork,
        shareMap,
        tests.NewTestingBeaconNodeWrapped(),
        net,
        km,
        opSigner,
) already has type runner.Runner (gosimple)
                return runner.NewVoluntaryExitRunner(
                       ^
protocol/v2/ssv/testing/runner.go:187:10: S1040: type assertion to the same type: ret already has type runner.Runner (gosimple)
                return ret.(runner.Runner)
                       ^
operator/validator/controller.go:936:8: lostcancel: the cancel function returned by context.WithCancel should be called, not discarded, to avoid a context leak (govet)
                ctx, _ := context.WithCancel(c.context)
                     ^
protocol/v2/testing/test_utils.go:283:4: printf: log.Fatalf format %s has arg header.Typeflag of wrong type byte (govet)
                        log.Fatalf(
                        ^
protocol/v2/ssv/validator/non_committee_validator.go:86:10: printf: fmt.Errorf format %s has arg partialSigMessages.Type of wrong type github.com/ssvlabs/ssv-spec/types.PartialSigMsgType (govet)
        [...]

2024-07-16 20:58 UTC, y0sher requested changes
fix rest of lint errs

2024-07-18 11:55 UTC, y0sher commented on protocol/v2/qbft/spectest/msg_processing_type.go
> +		qbfttesting.TestingConfig(logger, spectestingutils.KeySetForCommitteeMember(test.Pre.State.CommitteeMember), convert.RunnerRole(msgId.GetRoleType())),
`TestingConfig` should receive `spectypes.RunnerRole`, use the `convert.RunnerRole` only where required (db and exporter).
its like this in `alan/no-fork` already

2024-07-18 12:41 UTC, y0sher commented on protocol/v2/ssv/validator/committee.go
> +			logger.Warn("handles error message", zap.Error(err))
```suggestion
			logger.Error("❗ failed consuming committee queue", zap.Error(err))
```

2024-07-18 14:43 UTC, y0sher reviewed
@pavelkrolevets please review the p2p tests code

2024-07-21 09:02 UTC, y0sher commented
@guym-blox , the new p2p testing code lies here - https://github.com/ssvlabs/ssv/pull/1442 
if it passes we can use it here as well

2024-07-22 07:45 UTC, pavelkrolevets commented
> @guym-blox , the new p2p testing code lies here - #1442 if it passes we can use it here as well. Edit, from my last check, they do not pass, @pavelkrolevets can you confirm?

Checked p2p tests locally are passing `[alan/no-fork-fix-tests](https://github.com/ssvlabs/ssv/tree/alan/no-fork-fix-tests)`. Try to clean cache `go clean -cache`. Please let me know which test is failing Ill check it again.

2024-07-22 09:10 UTC, pavelkrolevets commented on network/p2p/p2p_test.go
> -	ln, routers, err := CreateNetworkAndSubscribeFromKeySet(t, ctx, LocalNetOptions{
You can reuse test from here https://github.com/ssvlabs/ssv/pull/1442

2024-07-23 10:35 UTC, y0sher commented
@pavelkrolevets since this PR is only taking care of Lint, please take care of the p2p tests in your branch.

2024-07-23 10:37 UTC, merged