this fix https://github.com/ssvlabs/ssv/issues/1565 (#1493) provide c…
ssvlabs/ssv pull request #1614
Opened 2024-08-12 12:09 UTC by guym-blox

…ustom domain and trusted peers

2024-08-12 13:12 UTC, y0sher approved these changes
lgtm

2024-08-13 09:24 UTC, moshe-blox requested changes

2024-08-13 09:24 UTC, moshe-blox commented on cli/operator/node.go
> +		logger.Info("running with custom domain type", fields.Domain(networkConfig.GenesisDomainType))
should probably add something like:
```suggestion
if networkConfig.PastAlanFork() {
    logger.Info("custom domain type is ineffective now after Alan fork", fields.Domain(networkConfig.GenesisDomainType))
} else {
    logger.Info("running with custom domain type", fields.Domain(networkConfig.GenesisDomainType))
}
```

2024-08-13 09:24 UTC, moshe-blox commented on network/p2p/p2p.go
> +	)
this part is unrelated to getConnector, could be extracted to logStartup or just moved back into Start()

2024-08-13 09:24 UTC, moshe-blox commented
well done, just 2 comments

2024-08-13 10:32 UTC, moshe-blox approved these changes

2024-08-13 10:33 UTC, merged