Fix: Run local nodes using local events
ssvlabs/ssv pull request #1688
Opened 2024-09-02 12:55 UTC by olegshmuelov

2024-09-03 14:36 UTC, y0sher approved these changes

2024-09-03 15:30 UTC, moshe-blox requested changes
great job 👍

2024-09-03 15:30 UTC, moshe-blox commented on Dockerfile
> +    dnsutils && \
the version should be hardcoded as this was a request from the last audit

you can find the correct latest version by running that golang image and using the apt-get command inside

2024-09-09 16:13 UTC, moshe-blox approved these changes

2024-09-09 16:26 UTC, merged