Validation package replace panic statements with errors
ssvlabs/ssv pull request #1726
Opened 2024-09-11 11:48 UTC by AKorpusenko

2024-09-11 13:10 UTC, moshe-blox commented on message/validation/consensus_validation.go
> +		return errors.Wrap(err, "failed to get max round")
iirc errors.Wrap is deprecated and fmt.Errorf has replaced it

2024-09-11 13:11 UTC, y0sher commented on message/validation/genesis/consensus_validation.go
> +		return consensusDescriptor, msgSlot, errors.Wrap(err, "failed to get max round")
ditto about fmt.Errorf

2024-09-11 13:13 UTC, y0sher requested changes
small changes :)

2024-09-15 08:29 UTC, y0sher approved these changes

2024-09-15 14:26 UTC, moshe-blox approved these changes

2024-09-15 14:26 UTC, merged