fix(exporter): ensure exporter node fetch metadata for all validators
ssvlabs/ssv pull request #1962
Opened 2024-12-22 16:04 UTC by olegshmuelov

fix https://github.com/ssvlabs/ssv/issues/1961

2024-12-22 16:29 UTC, y0sher requested changes
please fix my comment and the Unit tests.

2024-12-22 17:10 UTC, moshe-blox commented on operator/validator/controller.go
> +	mySubnets := c.network.FixedSubnets()
fixed

2024-12-23 08:27 UTC, y0sher approved these changes
Lets fix unit tests and merge

2024-12-23 09:20 UTC, moshe-blox approved these changes

2024-12-23 09:21 UTC, merged