beacon/goclient, eth/executionclient: support multiple nodes
ssvlabs/ssv pull request #1964
Opened 2024-12-23 17:39 UTC by nkryuchkov

- [ ] support multiple consensus nodes
- [ ] support multiple execution nodes

2024-12-30 10:55 UTC, y0sher commented on beacon/goclient/goclient.go
> +	err := assertSameSpec(opt.Context, consensusClients...)
we should add some comments about this and the above, the conditions to make multiple bn work together (dialable, same spec, version, etc..)

2024-12-30 10:58 UTC, y0sher commented on beacon/goclient/proposer.go
> +	// TODO: Make sure this the above is correct. Should we submit only to the node that returned the block?
we should test this code thoroughly. 
is it correct that other nodes might know the payload for a blinded block though?

2025-01-01 14:06 UTC, y0sher commented on beacon/goclient/proposer.go
> +	// TODO: Make sure this the above is correct. Should we submit only to the node that returned the block?
Trying to submit only to the node that provided the block is going to require more state management. if its not an issue to sent to all of them this solution is perferred for now.

2025-01-01 14:13 UTC, y0sher commented on cmd/tcpproxy/tcpproxy.go
can you explain more about this file?

2025-01-01 14:14 UTC, y0sher commented on eth/executionclient/config.go
> +	Addr                  string        `yaml:"ETH1Addr" env:"ETH_1_ADDR" env-required:"true" env-description:"Execution client WebSocket address. Supports multiple comma-separated addresses"`
maybe just have `[]string` ? AFAIK viper knows how to parse this.

2025-01-01 14:14 UTC, y0sher commented on eth/executionclient/execution_client.go
> +	}
as I said above, I think it makes more sense to pass a slice. and to the parsing on a higher level.

2025-01-01 14:16 UTC, y0sher commented on eth/executionclient/execution_client.go
> +		return nil, fmt.Errorf("execution clients' chain IDs are not same")
maybe give some more info, want, have?

2025-01-01 14:17 UTC, y0sher commented on eth/executionclient/execution_client.go
> +func (ec *ExecutionClient) assertSameChainIDs(ctx context.Context) (bool, error) {
since this returns err, it's recommended to propagate the error message here then print on a higher level. doing both can result in a lot of redundancy in the logs.

2025-01-01 14:18 UTC, y0sher commented on eth/executionclient/execution_client.go
> +		ec.clientsMu.RLock()
IMO this seems like too much concurrency primitives to do a simple thing. maybe we can just use context?

2025-01-01 14:19 UTC, y0sher commented on eth/executionclient/execution_client.go
> +	})
why not wrap it up with identical interface?

2025-01-01 14:32 UTC, y0sher commented on eth/executionclient/execution_client.go
is the `ec.client` changing? why do you need to protect it? how does this copy help if its all pointers?

2025-01-01 14:33 UTC, y0sher commented on eth/executionclient/execution_client.go
also why not just use `getHealthyClient` here?

2025-01-01 14:35 UTC, y0sher commented on eth/executionclient/managed_client.go
> +		mc.client = nil
why set it to nil ? isn't setting healthy enough?

2025-01-01 14:36 UTC, y0sher commented on eth/executionclient/managed_client.go
> +func (mc *ManagedClient) connect(ctx context.Context) error {
if this happens only once at startup maybe the mutex protection (for the client) is not needed

2025-01-01 14:36 UTC, y0sher commented on protocol/v2/blockchain/beacon/client.go
> +	BeaconNodeAddr string `yaml:"BeaconNodeAddr" env:"BEACON_NODE_ADDR" env-required:"true" env-description:"Beacon node address. Supports multiple comma-separated addresses'"`
the config parsing should now how to parse it to []string directly.

2025-01-01 14:37 UTC, y0sher requested changes
good job :)
some questions and comments.

2025-01-08 14:35 UTC, moshe-blox commented
I suggest instead of modifying ExecutionClient implementation to be a multiclient, we should declare an interface for the Ethereum client with only the methods we call, and a standalone Multiclient implementation that implements this interface.

This would mean that our ExecutionClient will not have to be changed at all (at least theoretically).

By the way, we should also think how to handle cases where subscriptions fail. AFAIK SubscribeNewHead is called on one of the Eth clients. What if that client dies? Would we cancel the subscription and call it again on the other client?

2025-01-09 19:55 UTC, nkryuchkov commented on cmd/tcpproxy/tcpproxy.go
This is just for testing. Setting up a real node looked more complex to me. so I used this TCP proxy to redirect all data to a beacon node and be able to shut it down to simulate outage. Although it doesn't simulate a case when the node is up but goes out of sync

2025-01-09 20:03 UTC, nkryuchkov commented on eth/executionclient/config.go
> +	Addr                  string        `yaml:"ETH1Addr" env:"ETH_1_ADDR" env-required:"true" env-description:"Execution client WebSocket address. Supports multiple comma-separated addresses"`
Then it won't be backward compatible with the current values everyone uses, so it would require changing configs. Also, I think a significant amount of operators will continue using just one node, so a slice parameter might be less convenient

2025-01-09 20:29 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
> +		return nil, fmt.Errorf("execution clients' chain IDs are not same")
@y0sher There are logs for each mismatch (`Chain ID mismatch`). Since there may be several clients, there may be several want's, so I thought having returning some generic error and printing a log for each mismatch would be better

2025-01-09 21:17 UTC, nkryuchkov commented on eth/executionclient/config.go
> +	Addr                  string        `yaml:"ETH1Addr" env:"ETH_1_ADDR" env-required:"true" env-description:"Execution client WebSocket address. Supports multiple comma-separated addresses"`
```bash
% ./bin/ssvnode start-node 
2025/01/09 18:15:53 could not create logger could not read config: config file parsing error: yaml: unmarshal errors:
  line 14: cannot unmarshal !!str `ws://pr...` into []string
```

2025-01-09 21:18 UTC, nkryuchkov commented on eth/executionclient/managed_client.go
> +func (mc *ManagedClient) connect(ctx context.Context) error {
in `attemptReconnect` too

2025-01-13 13:59 UTC, nkryuchkov commented on eth/executionclient/managed_client.go
> +		mc.client = nil
I just changed the implementation to use multi-client, so I'm resolving this

2025-01-13 13:59 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
I just changed the implementation to use multi-client, so I'm resolving this

2025-01-13 13:59 UTC, nkryuchkov commented on eth/executionclient/managed_client.go
> +func (mc *ManagedClient) connect(ctx context.Context) error {
I just changed the implementation to use multi-client, so I'm resolving this

2025-01-13 14:00 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
> +		ec.clientsMu.RLock()
fixed

2025-01-13 14:00 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
> +	}
done

2025-01-13 14:02 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
> +	})
can you please explain what you mean?

2025-01-15 11:40 UTC, y0sher commented on eth/executionclient/multi_client.go
> +				f := func(client SingleClientProvider) (any, error) {
this can be defined outside of the loop. even though compiler/runtime takes care of it anyway.

2025-01-15 11:53 UTC, y0sher commented on eth/executionclient/multi_client.go
> +				return
honestly I don't know if this is simpler or clearer, just shorter.. let me know what you think
```suggestion
				if err !=nil && !(errors.Is(err, ErrClosed) || errors.Is(err, context.Canceled)) {
					ec.logger.Fatal("failed to stream registry events", zap.Error(err))
				}
				return
```

2025-01-15 11:54 UTC, y0sher commented on eth/executionclient/multi_client.go
> +					return // Terminate the loop after logging Fatal
anyway no need to return after fatal since it stops the program.

2025-01-15 11:55 UTC, y0sher commented on eth/executionclient/multi_client.go
> +	}
I guess this should never happen since we check before initializing. we can leave it anyway..

2025-01-15 11:57 UTC, y0sher commented on eth/executionclient/multi_client.go
> +		client := ec.clients[currentIdx]
is `clients` ever changing ? I don't think there's a reason to lock it.

2025-01-15 11:58 UTC, y0sher requested changes
I like new version of execution multi better :) left a few comments.

2025-01-15 11:59 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +		client := ec.clients[currentIdx]
Only `currClientIdx` changes. Indeed, this line can be moved outside the lock

2025-01-15 13:53 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				f := func(client SingleClientProvider) (any, error) {
It needs to be a closure because `fromBlock` is updated inside

2025-01-15 13:58 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				return
I don't think we should call `Fatal` on client closure or context cancellation because they should indicate "successful closure", e.g. graceful shutdown if the pod is restarted. There won't be probably any difference in actual behavior but I'd prefer to keep process exit codes clean

2025-01-15 14:02 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				f := func(client SingleClientProvider) (any, error) {
I added a comment

2025-01-15 14:04 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				return
Sorry, I didn't read your suggestion well enough, so my previous message is wrong. Yes, we can do what you suggest

2025-01-15 14:08 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				return
Changed

2025-01-15 14:19 UTC, y0sher approved these changes
lgtm!

2025-01-15 16:26 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +	if _, err := ec.call(ec.setMethod(ctx, "Healthy"), f); err != nil {
IIRC it's a good standard in Go to have this as a func (rather than method) called `withMethod` and the key as an empty struct type

example: https://mainfunction.org/articles/golang-context-with-value-best-practices/

(we don't need the FromContext method)

2025-01-15 16:27 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +	if _, err := ec.call(ec.setMethod(ctx, "Healthy"), f); err != nil {
if withMethod conflicts with option funcs in this package (With<Option>) then we could maybe just call it `contextWithMethod` to be explicit

2025-01-15 18:26 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	if _, err := ec.call(ec.setMethod(ctx, "Healthy"), f); err != nil {
Yes, I agree, it doesn't have to be a method. Why don't we need the `FromContext` method? It makes extracting value easier

2025-01-16 11:53 UTC, moshe-blox commented
Potential problem with the execution multiclient is that if one client is synced but the other isn't then we might select the lower synced client in certain method calls such as when fetching logs or when checking for healthines.

What do you think? How should we solve this? @nkryuchkov @y0sher

2025-01-17 00:08 UTC, nkryuchkov commented
@moshe-blox I agree, IIRC there used to be some handling for this in the initial implementation but I didn't port it to the multi-client. Please review the recent commits. Perhaps we also need to check cached healthiness on each iteration in `streamLogsToChan`/`FetchHistoricalLogs` to switch to another client if the current one is out of sync

2025-01-19 14:19 UTC, y0sher commented on eth/executionclient/multi_client.go
> +func (ec *MultiClient) FetchHistoricalLogs(ctx context.Context, fromBlock uint64) (<-chan BlockLogs, <-chan error, error) {
Just fetching from a single client and then starting from scratch if is failed might be a smarter solution here. Since we sync history only on startup and its not a heavy long process, we should go with a simpler solution.

2025-01-19 14:46 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +	go client.reconnect(ctx)
this used to happen only in streaming, so we should either do the same, or rely on ethclient's built-in reconnection (requires properly testing it)

2025-01-19 14:49 UTC, moshe-blox commented on eth/executionclient/defaults.go
> +	DefaultHealthInvalidationInterval  = 10 * time.Second // TODO: decide on this value, for now choosing a bit less than block interval
this should be double the interval of NodeProber (i think 1 slot) to let it finish its own requests and avoid doing two in parallel

2025-01-19 14:52 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +				}
this can be removed as it happens inside `call`

2025-01-19 14:55 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +}
isn't it the same as just using `call` as before which should also return no error only if at least one is healthy?

2025-01-20 13:31 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +}
@moshe-blox if all clients are healthy, `call` would check only one client. The current `Healthy` implementation calls `Healthy` on all clients to update their state

2025-01-20 13:33 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +				}
yes, but we can quickly check here if there are any healthy clients to avoid proceeding if all clients are down

2025-01-20 13:35 UTC, nkryuchkov commented on eth/executionclient/defaults.go
> +	DefaultHealthInvalidationInterval  = 10 * time.Second // TODO: decide on this value, for now choosing a bit less than block interval
`NodeProber`'s interval is 24 seconds, so I thought it needed to be done more often. There should not be parallel requests because the healthiness is cached for a short time

2025-01-20 13:53 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +}
i see, that makes sense, thanks 👍

can you pls try using https://pkg.go.dev/github.com/sourcegraph/conc/pool#ErrorPool for this? i imagine it can simplify the code here quite a bit

it should handle concurrency and join the errors for you

plus you can just check that the err returned by `Wait` isn't nil instead of having `atLeastOneHealth`

2025-01-20 13:56 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +}
@moshe-blox great idea, as I understand it's similar to https://pkg.go.dev/golang.org/x/sync/errgroup, right? Do you have any objections against using `errgroup` instead?

2025-01-20 13:57 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +	return nil, fmt.Errorf("all clients returned an error")
can we pls return the joined errors? this is what the callers will see and it needs to be descriptive

fmt.Errorf("all clients failed: %w", ..)

2025-01-20 14:05 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	return nil, fmt.Errorf("all clients returned an error")
done

2025-01-20 14:05 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +func (ec *MultiClient) StreamLogs(ctx context.Context, fromBlock uint64) <-chan BlockLogs {
done

2025-01-20 14:09 UTC, moshe-blox commented on eth/executionclient/execution_client.go
> +}
i think if we add lock & defer unlock at the beginning of the func, it should solve the parallel request issue

the first parallel caller with lock and update time, the other caller will wait for lock and see that time updated and return immediately

2025-01-20 15:53 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +}
Actually, I'm not sure if it will look better because we need to return no error if at least one client is healthy, so it would require parsing the combined error

2025-01-20 16:14 UTC, nkryuchkov commented on eth/executionclient/execution_client.go
> +}
done

2025-01-21 09:58 UTC, y0sher approved these changes

2025-01-21 12:25 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	atLeastOne := atomic.Bool{}
@moshe-blox @y0sher I think `atLeastOne` is not clear enough, let's rename it to `atLeastOneHealthy`?

2025-01-21 12:26 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	return fmt.Errorf("no healthy clients: %w", err)
@moshe-blox @y0sher probably would be a bit more readable
```suggestion
	if atLeastOne.Load() {
		return nil
	}
	return fmt.Errorf("no healthy clients: %w", p.Wait())
```

2025-01-21 12:28 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	currentClientIndex atomic.Int64
really not a big deal, but perhaps `Uint64` would describe an index better

2025-01-21 12:51 UTC, moshe-blox commented on beacon/goclient/proposer.go
> +				cancel()
actually that wouldnt be enough because theres a `defer cancel()` lol

so we must wait for all

2025-01-21 13:19 UTC, y0sher commented on eth/executionclient/multi_client.go
> +	return fmt.Errorf("no healthy clients: %w", err)
but you must wait before you load the int to know that all goroutines are done.

2025-01-21 13:20 UTC, y0sher commented on eth/executionclient/multi_client.go
> +	currentClientIndex atomic.Int64
since indexing in go is an `int` by default which is int64 , I thought it'll be an easier cast than uint.

2025-01-21 13:39 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	return fmt.Errorf("no healthy clients: %w", err)
yes, you're right, maybe something like this to follow the happy path?

```suggestion
	if err := p.Wait(); err != nil && !atLeastOne.Load() {
			return fmt.Errorf("no healthy clients: %w", err)
	}
	return nil
```

2025-01-21 13:47 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +		mc.currentClientIndex.Store(int64(clientIndex))
Probably, there could be a case in which a node fails on some of the requests (e.g. some API subset is disabled), so the clients would be switched back and forth. But I'm not sure we need to do something with it now

2025-01-21 14:25 UTC, nkryuchkov commented on beacon/goclient/proposer.go
> +				cancel()
fixed, please review

2025-01-21 15:15 UTC, moshe-blox commented on eth/executionclient/multi_client.go
> +	return fmt.Errorf("no healthy clients: %w", err)
@nkryuchkov your first comment here is very readable IMO

```go
	err := p.Wait()
	if healthyClients.Load() > 0 {
		return nil
	}
	return fmt.Errorf("no healthy clients: %w", err)
```
i pushed this to avoid "atLeastOne" naming which i cant think of a good name for lol
(also did this in SubmitBlindedBeaconBlock)

WDYT?

2025-01-21 16:19 UTC, moshe-blox commented on beacon/goclient/goclient.go
>  }
i dont know the benefit of checking all of these

checking just `GENESIS_FORK_VERSION` should be sufficient, as it's supposed to be the "network ID"

2025-01-21 16:21 UTC, moshe-blox commented on beacon/goclient/goclient.go
>  }
i see that this variable is in genesis data, so essentially sameSpec isnt necessary

2025-01-21 17:37 UTC, nkryuchkov commented on beacon/goclient/goclient.go
>  }
I agree, done

2025-01-21 17:39 UTC, nkryuchkov commented on eth/executionclient/multi_client.go
> +	return fmt.Errorf("no healthy clients: %w", err)
@moshe-blox LGTM

2025-01-21 18:49 UTC, moshe-blox approved these changes

2025-01-21 21:38 UTC, merged